version: '3.9'

networks:
  net:
    driver: bridge

services:

  telegrambot:
    image: ${DOCKER_REGISTRY-}telegrambot
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
    networks:
      - net

  telegrambot.tests:
    image: ${DOCKER_REGISTRY-}telegrambottests
    build:
      context: .
      dockerfile: TelegramBot.Tests/Dockerfile
    depends_on:
      telegrambot:
        condition: service_healthy
    networks:
      - net
