version: '3.9'

networks:
  net:
    driver: bridge

services:

  chroma_server:
    image: chromadb/chroma:latest
    volumes:
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
      # Read more about deployments: https://docs.trychroma.com/deployment
      - chroma-data:/chroma/chroma
    restart: unless-stopped # possible values are: "no", always", "on-failure", "unless-stopped"
    ports:
      - "8000:8000"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/v2/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - net

  telegrambot:
    image: ${DOCKER_REGISTRY-}telegrambot
    build:
      context: .
      dockerfile: TelegramBot/Dockerfile
    depends_on:
      chroma_server:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_API_KEY=${TELEGRAM_BOT_API_KEY}
      - CHROMA_ENDPOINT=http://chroma_server:8000
    networks:
      - net 

volumes:
  chroma-data:
    driver: local