name: Build and deploy ASP.Net Core app to Azure Web App - aitelegrambot

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  integration_tests:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  build_before_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        run: dotnet build TelegramBot/TelegramBot.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish TelegramBot/TelegramBot.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy_to_azure:
    runs-on: ubuntu-latest
    needs: build_before_publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5CEEA9438C3C41A5A229D72930F50C39 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2EA2D9A83236472AA0C082407704C5BF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_18F6E82DC2DB44589D1FF87E9BC6849F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'aitelegrambot'
          slot-name: 'Production'
          package: .
